<?php

return [
    /**
     * The Template Attributes
     */
    'attributes' => [
        'size',
        'creature_race',
        'alignment',
        'armor_class',
        'hit_points',
        'speed',
        'str',
        'dex',
        'con',
        'int',
        'wis',
        'cha',
        'saving_throws',
        'skills',
        'damage_resistances',
        'damage_immunities',
        'condition_immunities',
        'senses',
        'languages',
        'challenge_rating',
        'spells_at_will',
        'spells_once',
        'spells_three',
        'feature_1' => ['type' => 8],
        'feature_2' => ['type' => 8],
        'feature_3' => ['type' => 8],
        'multiattack',
        'attack_1' => ['type' => 8],
        'attack_2' => ['type' => 8],
        'attack_3' => ['type' => 8],
        'ability_1' => ['type' => 8],
        'ability_2' => ['type' => 8],
        'ability_3' => ['type' => 8],
        'reaction_1' => ['type' => 8],
        'reaction_2' => ['type' => 8],
        'reaction_3' => ['type' => 8],
        'innate_spellcasting' => ['type' => 8],
        'magic_resistance' => ['type' => 8],
        'magic_weapons' => ['type' => 8],
        'regeneration' => ['type' => 8],
        'legendary_resistance' => ['type' => 8],
        'legendary_action_1' => ['type' => 8],
        'legendary_action_2' => ['type' => 8],
        'legendary_action_3' => ['type' => 8],
        'legendary_resistance_count',
        'legendary_actions' => ['type' => 8],
    ]
];